# Generated by Django 5.1.5 on 2025-02-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
