# Generated by Django 5.1.4 on 2024-12-28 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('winners', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enter_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Registering', 'Registering'), ('Unregistered', 'Unregistered')], default='Unregistered', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_number', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('card-to-card', 'card-to-card'), ('payment-gateway', 'payment-gateway')], default='card-to-card', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('lottery_time', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('total_unread_messages', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_payments', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('sender_picture', models.ImageField(blank=True, upload_to='img/uploads/')),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer_picture', models.ImageField(blank=True, upload_to='img/uploads/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='panel.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(blank=True, default='2024-12-28T10:43:29.072096+00:00')),
                ('ticket', models.CharField(blank=True, default='34e3fc98', max_length=255, null=True)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Registering', 'Registering'), ('Unregistered', 'Unregistered')], default='Unregistered', max_length=20)),
                ('ticket_picture', models.ImageField(blank=True, upload_to='img/uploads/')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('payment_picture', models.ImageField(blank=True, upload_to='img/uploads/')),
                ('winning', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lottery_game', to='panel.games')),
                ('friends', models.ManyToManyField(blank=True, related_name='lottery_friends', to='panel.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_entries', to='panel.profile')),
            ],
        ),
        migrations.CreateModel(
            name='profileFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to='panel.profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_friend_set', to='panel.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, through='panel.profileFriend', to='panel.profile'),
        ),
    ]
