# Generated by Django 5.1.4 on 2025-01-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='register_date',
            field=models.DateTimeField(blank=True, default='2025-01-08T21:34:14.692080+00:00'),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='8b8c66e3', max_length=255, null=True),
        ),
    ]
