# Generated by Django 5.1.5 on 2025-02-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_lottery_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='91fae62b', max_length=255, null=True),
        ),
    ]
