# Generated by Django 5.1.4 on 2025-01-11 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_lottery_register_date_alter_lottery_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='register_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 11, 21, 48, 26, 115280, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='67b52eac', max_length=255, null=True),
        ),
    ]
