# Generated by Django 5.1.4 on 2025-01-11 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_lottery_register_date_alter_lottery_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='register_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='661b1531', max_length=255, null=True),
        ),
    ]
