# Generated by Django 5.1.4 on 2025-01-29 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_lottery_register_date_alter_lottery_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='d9110b6e', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('payment_method', models.CharField(choices=[('card_to_card', 'Card-to-Card Transfer'), ('gateway', 'Payment Gateway')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('receiver_card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_payment', to='panel.lottery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
