# Generated by Django 5.1.5 on 2025-02-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_rename_gateway_transaction_id_payment_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread_message_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='55e7c237', max_length=255, null=True),
        ),
    ]
