# Generated by Django 5.1.5 on 2025-02-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_profile_unread_message_number_alter_lottery_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='is_lottery_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='83df17e2', max_length=255, null=True),
        ),
    ]
