# Generated by Django 5.1.5 on 2025-02-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_lottery_ticket_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='cb35ed8c', max_length=255, null=True),
        ),
    ]
