# Generated by Django 5.1.5 on 2025-02-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_lottery_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='card_cvv',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='card_expire',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='d4a17063', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='card_number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
