# Generated by Django 5.1.5 on 2025-02-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_setting_is_lottery_started_alter_lottery_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread_payment_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='0f84518e', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unread_message_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
