# Generated by Django 5.1.5 on 2025-02-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_profile_unread_payment_number_alter_lottery_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='ac316638', max_length=255, null=True),
        ),
    ]
