# Generated by Django 5.1.5 on 2025-02-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_setting_card_cvv_setting_card_expire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='487068ad', max_length=255, null=True),
        ),
    ]
