# Generated by Django 5.1.5 on 2025-02-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_lottery_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='card_expire',
        ),
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='6b06cc24', max_length=255, null=True),
        ),
    ]
