# Generated by Django 5.1.5 on 2025-02-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_remove_setting_card_cvv_remove_setting_card_expire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='b8c35756', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='card_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
