# Generated by Django 5.1.5 on 2025-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_lottery_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='ticket',
            field=models.CharField(blank=True, default='a9229c08', max_length=255, null=True),
        ),
    ]
